server:
  port: 8083
spring:
  application:
    name: s-goma

  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: s-goma
      authentication-database: admin
      port: 27017